language: cpp

compiler: gcc

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y swig libc6-i386 lib32stdc++6 make g++
  - sudo apt-get install -y python python-setuptools python-numpy python-pandas python-matplotlib python-cogent python-imaging python-qt4 python-pip python-lxml
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted"
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  - sudo easy_install ete2
  - sudo easy_install hcluster

install:
  - cd src
  - make clean
  - make all
  - cd libs/jellyfish-2.1.3
  - make clean
  - ./configure
  - make
  - cd ../..
  - cd ../scripts

script:
  - ./cnidaria.py -h
