language: cpp

compiler: gcc

sudo: required

before_install:
  - sudo apt-add-repository ppa:boost-latest -y
  - sudo apt-add-repository ppa:mapnik/boost-backports-1-54 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get clean -qq
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.48-all-dev swig libc6-i386 lib32stdc++6 make
  - sudo apt-get install -y python python-setuptools python-numpy python-pandas python-matplotlib python-cogent python-imaging python-qt4 python-pip python-lxml
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - sudo easy_install ete2
  - sudo easy_install hcluster

install:
  - cd src
  - make clean
  - make all
  - cd libs/jellyfish-2.1.3
  - make clean
  - ./configure
  - make
  - cd ../..
  - cd ../scripts

script:
  - ./cnidaria.py -h
