language: cpp

compiler: gcc

before_script:
  - apt-get install -y libboost-all-dev swig libc6-i386 lib32stdc++6 make g++
  - apt-get install -y python python-setuptools python-numpy python-pandas python-matplotlib python-cogent python-imaging python-qt4 python-pip python-lxml
  - easy_install ete2
  - easy_install hcluster

install:
  - cd src
  - make clean
  - make all
  - cd libs/jellyfish-2.1.3
  - make clean
  - ./configure
  - make
  - cd ../..
  - cd ../scripts

script:
  - ./cnidaria.py -h
